export { default } from "./src/morpho-protocol-evm.js";
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type BorrowOptions = import("@tetherto/wdk-wallet/protocols").BorrowOptions;
export type BorrowResult = import("@tetherto/wdk-wallet/protocols").BorrowResult;
export type SupplyOptions = import("@tetherto/wdk-wallet/protocols").SupplyOptions;
export type SupplyResult = import("@tetherto/wdk-wallet/protocols").SupplyResult;
export type WithdrawOptions = import("@tetherto/wdk-wallet/protocols").WithdrawOptions;
export type WithdrawResult = import("@tetherto/wdk-wallet/protocols").WithdrawResult;
export type RepayOptions = import("@tetherto/wdk-wallet/protocols").RepayOptions;
export type RepayResult = import("@tetherto/wdk-wallet/protocols").RepayResult;
export type AccountData = import("./src/morpho-protocol-evm.js").AccountData;
export type VaultPosition = import("./src/morpho-protocol-evm.js").VaultPosition;
export type MarketPosition = import("./src/morpho-protocol-evm.js").MarketPosition;
export type MorphoProtocolOptions = import("./src/morpho-protocol-evm.js").MorphoProtocolOptions;
export { MORPHO_MARKET_PRESETS, MORPHO_VAULT_PRESETS } from "./src/morpho-presets.js";
